### ISSUE TITLE
babelify

### ISSUE THREAD

**Issue by gandhiShepard** [mattdesl/budo-gulp-starter#1]
So this is great. But I updated all the packages and Babelify doesn't work anymore. Do I need to alter this line? `transform: babelify` so a new configuration for es2015?

**Comment by mattdesl** [comment]
Yes things have changed in recent babelify. You need to set a preset like this: 
https://github.com/mattdesl/codevember/blob/a835e4d1d347f30db738e12510d1fed2c778d2f7/dev.js#L27

Also this is using a fairly old version of `budo` (it's on `6.x` now). I will update this repo when I get a chance, but definitely take a look through the docs and changelog to see what's new.  :smile: 
https://github.com/mattdesl/budo

`garnish` is now included by default, `verbose` is no longer needed, you can use `open: true` as an option, and browserify options like `transform` and `plugin` are now placed inside a `browserify: {...}` field.

Also if you want to get more advanced, you can use the new `middleware` feature in budo which would allow for SASS/LESS to be integrated without writing to disk (i.e. should be faster during dev). 

https://github.com/mattdesl/budo-less/blob/master/test/api-example.js

**Comment by mattdesl** [comment]
I will update this repo now, actually, and let you know.

**Comment by mattdesl** [comment]
Ok, should be all good. Refer to this repo for how you can set up your project with gulp + SASS + budo + browserify. :smile:

**Comment by gandhiShepard** [comment]
Hell yeah! Thanks! Rock on! 

![hqbjc](https://cloud.githubusercontent.com/assets/8546059/11020722/f4a53cd8-85ed-11e5-80ee-99821c1ae2f9.gif)
